### ISSUE TITLE
Add ardusnake library as a git submodule

### ISSUE THREAD

**Issue by Obijuan** [bq/zowi#4]
For testing zowi's gaits you have to install the ardusnake library, that is an independent project. It would be great if it is included as a git submodule

There are more infor about git submodules here:

https://geekytheory.com/submodulos-de-git-que-son-y-por-que-usarlos/

**Comment by JavierIH** [comment]
Good idea Obijuan, It's done!

**Comment by David-Estevez** [comment]
Remember to put in the corresponding README.md the following clone command:

git clone --recursive https://github.com/bq/zowi.git

That will download all the submodules automatically when cloning the main repo. If not, you have to init the submodule and update it in order to have the library, which can be non-intuitive for a user that has never worked with git submodules.

Maybe in the root README?

**Comment by JavierIH** [comment]
Thanks for the advice David. The entire repo needs a deep update on the README files, so i'll be including this with the next commit.
